//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityClubs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClubMembership
    {
        public int UniversityId { get; set; }
        public int ClubId { get; set; }
        public string Status { get; set; }
        public string EnrollDate { get; set; }
        public string Role { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual User User { get; set; }
    }
}
