//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityClubs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Date { get; set; }
        public string Location { get; set; }
        public string ImagePath { get; set; }
        public int ClubId { get; set; }
        public Nullable<int> Capacity { get; set; }
        public string UniqueCode { get; set; }
        public Nullable<int> ParticipantsCount { get; set; }
    
        public virtual Club Club { get; set; }
    }
}
